name: "Dependabot Automerge - Action"

on:
  pull_request_target:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.8
        with:
          ignoreActions: worker,WIP,Automerge PRs
          checkInterval: 37
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automerge'
        uses: pascalgn/automerge-action@v0.16.3
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_LABELS: "dependencies"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DELETE_BRANCH: true
