# https://github.com/marketplace/actions/publish-nuget
name: Publish to Nuget
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: ../UnitTest
          report_title: Unit Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_build_on_failed_tests: true

  publish:
    needs: unit-test
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Publish
      - name: Publish on Version Change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: BindableProps/BindableProps.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
